media:
  - name: assets
    input: src/assets
    output: /assets
    rename: safe

content:
  - name: pages
    label: Stránky
    type: collection
    path: src
    exclude:
      ["_data", "_includes", "assets", "css", "novinky", "program", "404.md"]
    fields:
      - name: title
        label: Název
        type: string
        required: true
      - name: description
        label: Popisek
        description: Popisek stránky pro SEO
        type: text
      - name: draft
        label: Koncept
        description: "Pokud je zaškrtnuto, stránka se nebude zobrazovat na produkci"
        type: boolean
        default: false
      - name: body
        label: Obsah
        type: rich-text

  - name: news
    label: Novinky
    type: collection
    path: src/novinky
    fields:
      - name: title
        label: Nadpis
        type: string
        description: "Nadpis je automaticky vložen jako hlavní nadpis. Pro další podnadpisy je proto nutné použít nejvýše první úroveň podnadpisů."
        required: True
      - name: date
        label: Datum
        type: date
        required: True
        options:
          time: False
          format: yyyy-MM-dd
      - name: draft
        label: Koncept
        description: "Pokud je zaškrtnuto, stránka se nebude zobrazovat na produkci"
        type: boolean
        default: false
      - name: body
        label: Obsah
        type: rich-text
        options:
          media: assets
          path: src/assets/novinky
          rename: safe

  - name: program
    label: Program
    type: collection
    path: src/program
    fields:
      - name: title
        label: Název
        type: string
        required: true
      - name: index
        label: Číslo (pro řazení)
        type: number
        options:
          min: 1
          max: 100
      - name: photo
        label: Fotka
        type: image
        options:
          media: assets
          path: src/assets/program
      - name: body
        label: Obsah
        type: rich-text
    view:
      default:
        sort: index
        order: asc

  - name: candidates
    label: Kandidáti
    type: file
    path: src/_data/candidates.json
    list: True
    fields:
      - name: name
        label: Jméno
        type: string
        required: true
      - name: work
        label: Zaměstnání
        type: string
      - name: bio
        label: Popisek
        type: rich-text
      - name: photo
        label: Fotka
        type: image

actions:
  - name: deploy
    label: Nasadit stránky na produkci
    workflow: merge-prod.yml
    confirm:
      title: Nasazení stránek na produkci
      message: Opravdu chceš nasadit a zveřejnit aktuální obsah na produkční verzi?
      button: Ano, nasadit

settings:
  commit:
    identity: app
    templates:
      create: "cms(create): {path}"
      update: "cms(update): {path}"
      delete: "cms(delete): {path}"
      rename: "cms(rename): {oldPath} -> {newPath}"
